import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from '@/config/modules/fuel-operation/fuel-operation-page-factory'

const routeRoot = import.meta.env.VITE_API_ROUTE_COMPLIANCE || '/compliance'
const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const caseFields = [...identity('Case Name', 'Case Reference'), field('account_id', 'Account ID', 'number'), field('risk_level', 'Risk Level'), field('assigned_to', 'Assigned To'), field('opened_date', 'Opened Date', 'date'), field('review_date', 'Review Date', 'date'), field('notes', 'Notes', 'textarea')]
const eventFields = [...identity('Event', 'Event Reference'), field('event_type', 'Event Type'), field('severity', 'Severity'), field('event_date', 'Event Date', 'datetime'), field('user_id', 'User ID', 'number'), field('ip_address', 'IP Address'), field('description', 'Description', 'textarea')]
const def = (slug: string, title: string, description: string, fields: FuelOperationField[], readOnly = false): FuelOperationDefinition => ({ slug, title, description, fields, routeRoot, idPrefix: 'compliance', icon: 'Circle', readOnly })

const definitions: FuelOperationDefinition[] = [
  def('compliance-dashboard', 'Compliance Dashboard', 'Review compliance posture, active cases, risks, and incidents.', [...identity('Metric', 'Metric Code'), field('open_cases', 'Open Cases', 'number'), field('high_risk_cases', 'High-Risk Cases', 'number'), field('open_incidents', 'Open Incidents', 'number'), field('expiring_licences', 'Expiring Licences', 'number')], true),
  def('kyc-verification', 'KYC Verification', 'Manage know-your-customer verification cases.', [...caseFields, field('customer_id', 'Customer ID', 'number'), field('identity_number', 'Identity Number'), field('verification_result', 'Verification Result')]),
  def('kyb-verification', 'KYB Verification', 'Manage know-your-business verification cases.', [...caseFields, field('business_id', 'Business ID', 'number'), field('registration_number', 'Registration Number'), field('beneficial_owners_verified', 'Owners Verified')]),
  def('customer-risk-profiles', 'Customer Risk Profiles', 'Manage customer compliance and financial risk profiles.', [...caseFields, field('customer_id', 'Customer ID', 'number', true), field('risk_score', 'Risk Score', 'number'), field('risk_factors', 'Risk Factors', 'textarea')]),
  def('transaction-monitoring', 'Transaction Monitoring', 'Monitor transactions against compliance rules and thresholds.', [...identity('Monitoring Alert', 'Alert Reference'), field('transaction_id', 'Transaction ID', 'number'), field('account_id', 'Account ID', 'number'), field('rule', 'Triggered Rule'), field('risk_score', 'Risk Score', 'number'), field('detected_date', 'Detected Date', 'datetime')], true),
  def('suspicious-transactions', 'Suspicious Transactions', 'Investigate transactions flagged as suspicious.', [...caseFields, field('transaction_id', 'Transaction ID', 'number', true), field('amount', 'Amount', 'currency'), field('suspicion_reason', 'Suspicion Reason', 'textarea'), field('reported_to_authority', 'Reported to Authority')]),
  def('fuel-variance-investigations', 'Fuel Variance Investigations', 'Investigate material stock, delivery, and sales variances.', [...caseFields, field('station_id', 'Station ID', 'number'), field('product_id', 'Product ID', 'number'), field('expected_quantity', 'Expected Quantity', 'number'), field('actual_quantity', 'Actual Quantity', 'number'), field('variance', 'Variance', 'number')]),
  def('regulatory-reports', 'Regulatory Reports', 'Review regulatory submissions and reporting status.', [...identity('Regulatory Report', 'Report Reference'), field('report_type', 'Report Type'), field('reporting_period', 'Reporting Period'), field('submission_date', 'Submission Date', 'date'), field('authority', 'Regulatory Authority'), field('document_url', 'Document URL', 'url')], true),
  def('licence-management', 'Licence Management', 'Manage operating and regulatory licences.', [...identity('Licence', 'Licence Number'), field('entity_id', 'Entity ID', 'number'), field('licence_type', 'Licence Type', 'text', true), field('issuing_authority', 'Issuing Authority'), field('issue_date', 'Issue Date', 'date'), field('expiry_date', 'Expiry Date', 'date', true), field('document_url', 'Document URL', 'url')]),
  def('insurance-management', 'Insurance Management', 'Manage insurance policies and coverage records.', [...identity('Insurance Policy', 'Policy Number'), field('entity_id', 'Entity ID', 'number'), field('insurance_type', 'Insurance Type', 'text', true), field('provider', 'Provider'), field('coverage_amount', 'Coverage Amount', 'currency'), field('start_date', 'Start Date', 'date'), field('expiry_date', 'Expiry Date', 'date')]),
  def('risk-register', 'Risk Register', 'Maintain organizational compliance and operational risks.', [...identity('Risk', 'Risk Reference'), field('risk_category', 'Risk Category'), field('likelihood', 'Likelihood'), field('impact', 'Impact'), field('risk_score', 'Risk Score', 'number'), field('owner', 'Risk Owner'), field('mitigation', 'Mitigation', 'textarea')]),
  def('compliance-inspections', 'Compliance Inspections', 'Plan and record compliance inspections.', [...identity('Inspection', 'Inspection Number'), field('entity_id', 'Entity ID', 'number'), field('inspection_type', 'Inspection Type'), field('inspection_date', 'Inspection Date', 'date', true), field('inspector', 'Inspector'), field('result', 'Result'), field('findings', 'Findings', 'textarea')]),
  def('compliance-incidents', 'Compliance Incidents', 'Record and resolve compliance incidents.', [...caseFields, field('incident_type', 'Incident Type'), field('severity', 'Severity'), field('incident_date', 'Incident Date', 'datetime'), field('description', 'Description', 'textarea'), field('resolution', 'Resolution', 'textarea')]),
  def('fraud-reports', 'Fraud Reports', 'Record and investigate suspected fraud.', [...caseFields, field('fraud_type', 'Fraud Type'), field('amount', 'Amount', 'currency'), field('reported_date', 'Reported Date', 'datetime'), field('reported_by', 'Reported By'), field('description', 'Description', 'textarea')]),
  def('audit-logs', 'Audit Logs', 'Review immutable system and data-change audit events.', eventFields, true),
  def('user-activity-logs', 'User Activity Logs', 'Review user actions performed across the platform.', [...eventFields, field('action', 'Action'), field('resource', 'Resource')], true),
  def('security-events', 'Security Events', 'Review authentication, authorization, and security events.', [...eventFields, field('resolution_status', 'Resolution Status')], true),
  def('login-attempts', 'Login Attempts', 'Review successful and failed authentication attempts.', [...identity('Login Attempt', 'Attempt Reference'), field('user_id', 'User ID', 'number'), field('email', 'Email', 'email'), field('ip_address', 'IP Address'), field('attempt_date', 'Attempt Date', 'datetime'), field('result', 'Result'), field('failure_reason', 'Failure Reason')], true),
]

export const complianceConfigs = definitions.map(createFuelOperationPage)
export const compliancePageRegistry = Object.fromEntries(complianceConfigs.map((page) => [page.id, page]))
