import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from '@/config/modules/fuel-operation/fuel-operation-page-factory'

const routeRoot = import.meta.env.VITE_API_ROUTE_REPORTS || '/reports'
const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Report Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const period = [field('period_start', 'Period Start', 'date'), field('period_end', 'Period End', 'date'), field('generated_at', 'Generated At', 'datetime')]
const financial = [field('transaction_count', 'Transactions', 'number'), field('quantity', 'Quantity', 'number'), field('gross_amount', 'Gross Amount', 'currency'), field('net_amount', 'Net Amount', 'currency'), field('variance', 'Variance', 'currency')]
const performance = [field('target', 'Target', 'number'), field('actual', 'Actual', 'number'), field('variance', 'Variance', 'number'), field('performance_score', 'Performance Score', 'number')]
const def = (slug: string, title: string, description: string, fields: FuelOperationField[], readOnly = true): FuelOperationDefinition => ({ slug, title, description, fields, routeRoot, idPrefix: 'reports', icon: 'Circle', readOnly })

const definitions: FuelOperationDefinition[] = [
  def('reports-dashboard', 'Reports Dashboard', 'Review available reports, recent runs, and reporting activity.', [...identity('Report Metric', 'Metric Code'), field('report_count', 'Reports', 'number'), field('scheduled_count', 'Scheduled Reports', 'number'), field('downloads', 'Downloads', 'number'), ...period]),
  def('sales-reports', 'Sales Reports', 'Analyze fuel sales by product, station, customer, and period.', [...identity('Sales Report'), field('station', 'Station'), field('product', 'Product'), ...financial, ...period]),
  def('transaction-reports', 'Transaction Reports', 'Analyze transactions across channels and statuses.', [...identity('Transaction Report'), field('transaction_type', 'Transaction Type'), field('payment_method', 'Payment Method'), ...financial, ...period]),
  def('fuel-consumption-reports', 'Fuel Consumption Reports', 'Analyze fuel consumption by account, vehicle, and driver.', [...identity('Consumption Report'), field('account', 'Account'), field('vehicle', 'Vehicle'), field('driver', 'Driver'), field('litres_consumed', 'Litres Consumed', 'number'), field('consumption_value', 'Consumption Value', 'currency'), ...period]),
  def('inventory-reports', 'Inventory Reports', 'Analyze stock positions, movements, and valuation.', [...identity('Inventory Report'), field('location', 'Location'), field('product', 'Product'), field('opening_stock', 'Opening Stock', 'number'), field('closing_stock', 'Closing Stock', 'number'), field('stock_value', 'Stock Value', 'currency'), ...period]),
  def('station-reports', 'Station Reports', 'Review station operations, sales, inventory, and performance.', [...identity('Station Report'), field('station', 'Station'), field('sales_volume', 'Sales Volume', 'number'), field('revenue', 'Revenue', 'currency'), ...performance, ...period]),
  def('customer-reports', 'Customer Reports', 'Review customer usage, balances, and transaction activity.', [...identity('Customer Report'), field('customer', 'Customer'), field('account_number', 'Account Number'), field('balance', 'Balance', 'currency'), ...financial, ...period]),
  def('omc-reports', 'OMC Reports', 'Review oil marketing company sales and network performance.', [...identity('OMC Report'), field('omc', 'Oil Marketing Company'), field('station_count', 'Stations', 'number'), field('sales_volume', 'Sales Volume', 'number'), field('revenue', 'Revenue', 'currency'), ...period]),
  def('vehicle-reports', 'Vehicle Reports', 'Analyze vehicle fuel usage, limits, and activity.', [...identity('Vehicle Report'), field('vehicle', 'Vehicle'), field('registration_number', 'Registration Number'), field('fuel_consumed', 'Fuel Consumed', 'number'), field('fuel_cost', 'Fuel Cost', 'currency'), ...period]),
  def('driver-reports', 'Driver Reports', 'Analyze driver fuel usage and operational performance.', [...identity('Driver Report'), field('driver', 'Driver'), field('employee_number', 'Employee Number'), field('fuel_consumed', 'Fuel Consumed', 'number'), ...performance, ...period]),
  def('card-reports', 'Card Reports', 'Review card inventory, issuance, usage, and status.', [...identity('Card Report'), field('card_number', 'Card Number'), field('card_status', 'Card Status'), ...financial, ...period]),
  def('pos-reports', 'POS Reports', 'Review POS device transactions, settlements, and availability.', [...identity('POS Report'), field('terminal_id', 'Terminal ID'), field('station', 'Station'), field('uptime', 'Uptime', 'number'), ...financial, ...period]),
  def('delivery-reports', 'Delivery Reports', 'Analyze delivery fulfilment, quantities, and exceptions.', [...identity('Delivery Report'), field('delivery_number', 'Delivery Number'), field('destination', 'Destination'), field('ordered_quantity', 'Ordered Quantity', 'number'), field('delivered_quantity', 'Delivered Quantity', 'number'), field('delivery_variance', 'Variance', 'number'), ...period]),
  def('payment-reports', 'Payment Reports', 'Analyze customer and supplier payments.', [...identity('Payment Report'), field('payment_type', 'Payment Type'), field('payment_method', 'Payment Method'), ...financial, ...period]),
  def('financial-reports', 'Financial Reports', 'Review financial position, income, expenditure, and balances.', [...identity('Financial Report'), field('report_type', 'Report Type'), field('income', 'Income', 'currency'), field('expenditure', 'Expenditure', 'currency'), field('balance', 'Balance', 'currency'), ...period]),
  def('reconciliation-reports', 'Reconciliation Reports', 'Review reconciliation outcomes across operational systems.', [...identity('Reconciliation Report'), field('reconciliation_type', 'Reconciliation Type'), field('system_total', 'System Total', 'currency'), field('verified_total', 'Verified Total', 'currency'), field('variance', 'Variance', 'currency'), ...period]),
  def('variance-reports', 'Variance Reports', 'Analyze stock, transaction, and delivery variances.', [...identity('Variance Report'), field('variance_type', 'Variance Type'), field('expected_value', 'Expected Value', 'number'), field('actual_value', 'Actual Value', 'number'), field('variance', 'Variance', 'number'), ...period]),
  def('compliance-reports', 'Compliance Reports', 'Review compliance cases, risks, incidents, and licences.', [...identity('Compliance Report'), field('report_type', 'Report Type'), field('open_items', 'Open Items', 'number'), field('resolved_items', 'Resolved Items', 'number'), field('high_risk_items', 'High-Risk Items', 'number'), ...period]),
  def('audit-reports', 'Audit Reports', 'Review audited activity and data changes.', [...identity('Audit Report'), field('actor', 'Actor'), field('action', 'Action'), field('resource', 'Resource'), field('event_count', 'Events', 'number'), ...period]),
  def('performance-analytics', 'Performance Analytics', 'Analyze operational and financial performance trends.', [...identity('Performance Analysis'), field('business_area', 'Business Area'), ...performance, ...period]),
  def('forecasting', 'Forecasting', 'Review demand, sales, inventory, and financial forecasts.', [...identity('Forecast'), field('forecast_type', 'Forecast Type'), field('forecast_period', 'Forecast Period'), field('forecast_value', 'Forecast Value', 'number'), field('confidence', 'Confidence', 'number'), ...period]),
  def('kpi-dashboard', 'KPI Dashboard', 'Review key operational and financial indicators.', [...identity('KPI', 'KPI Code'), field('category', 'Category'), ...performance, ...period]),
  def('custom-report-builder', 'Custom Report Builder', 'Create reusable report definitions with selected fields and filters.', [...identity('Custom Report', 'Report Code'), field('data_source', 'Data Source', 'text', true), field('selected_fields', 'Selected Fields', 'textarea', true), field('filter_definition', 'Filter Definition', 'textarea'), field('sort_definition', 'Sort Definition', 'textarea')], false),
  def('scheduled-reports', 'Scheduled Reports', 'Manage recurring report generation and delivery schedules.', [...identity('Scheduled Report', 'Schedule Code'), field('report_id', 'Report ID', 'number', true), field('frequency', 'Frequency', 'text', true), field('next_run', 'Next Run', 'datetime'), field('recipients', 'Recipients', 'textarea'), field('output_format', 'Output Format')], false),
  def('download-centre', 'Download Centre', 'Review and download generated report files.', [...identity('Report File', 'Download Reference'), field('report_type', 'Report Type'), field('file_format', 'File Format'), field('file_size', 'File Size', 'number'), field('generated_at', 'Generated At', 'datetime'), field('download_url', 'Download URL', 'url')]),
]

export const reportsConfigs = definitions.map(createFuelOperationPage)
export const reportsPageRegistry = Object.fromEntries(reportsConfigs.map((page) => [page.id, page]))
