import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from '@/config/modules/fuel-operation/fuel-operation-page-factory'

const routeRoot = import.meta.env.VITE_API_ROUTE_FLEET || '/fleet'
const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const vehicle = [field('vehicle_id', 'Vehicle ID', 'number', true), field('registration_number', 'Registration Number'), field('make', 'Make'), field('model', 'Model')]
const driver = [field('driver_id', 'Driver ID', 'number', true), field('driver_name', 'Driver Name'), field('employee_number', 'Employee Number')]
const definition = (slug: string, title: string, description: string, fields: FuelOperationField[], options: Partial<FuelOperationDefinition> = {}): FuelOperationDefinition => ({ slug, title, description, fields, routeRoot, idPrefix: 'fleet', icon: 'Circle', ...options })

const vehicleFields = [...identity('Vehicle Name', 'Registration Number'), field('category_id', 'Category ID', 'number'), field('group_id', 'Group ID', 'number'), field('account_id', 'Customer Account ID', 'number'), field('make', 'Make', 'text', true), field('model', 'Model', 'text', true), field('year', 'Year', 'number'), field('fuel_type', 'Fuel Type'), field('tank_capacity', 'Tank Capacity', 'number')]
const driverFields = [...identity('Driver Name', 'Employee Number'), field('phone', 'Phone'), field('email', 'Email', 'email'), field('licence_number', 'Licence Number', 'text', true), field('licence_class', 'Licence Class'), field('licence_expiry', 'Licence Expiry', 'date')]

const definitions: FuelOperationDefinition[] = [
  definition('all-vehicles', 'All Vehicles', 'Manage all customer and operational vehicles.', vehicleFields, { createSlug: 'add-vehicle', createId: 'fleet-add-vehicle' }),
  definition('vehicle-categories', 'Vehicle Categories', 'Manage vehicle classification categories.', [...identity('Category Name', 'Category Code'), field('description', 'Description', 'textarea')]),
  definition('vehicle-groups', 'Vehicle Groups', 'Manage operational and customer vehicle groups.', [...identity('Group Name', 'Group Code'), field('account_id', 'Account ID', 'number'), field('description', 'Description', 'textarea')]),
  definition('customer-vehicles', 'Customer Vehicles', 'Review vehicles assigned to customer accounts.', [...vehicleFields, field('customer_name', 'Customer')], { readOnly: true }),
  definition('delivery-vehicles', 'Delivery Vehicles', 'Review vehicles assigned to delivery operations.', [...vehicleFields, field('current_driver', 'Current Driver'), field('availability', 'Availability')], { readOnly: true }),
  definition('tanker-trucks', 'Tanker Trucks', 'Review tanker trucks and carrying capacity.', [...vehicleFields, field('compartments', 'Compartments', 'number'), field('certification_expiry', 'Certification Expiry', 'date')], { readOnly: true }),
  definition('vehicle-documents', 'Vehicle Documents', 'Manage registration, insurance, and compliance documents.', [...identity('Document Name', 'Document Number'), ...vehicle, field('document_type', 'Document Type', 'text', true), field('issue_date', 'Issue Date', 'date'), field('expiry_date', 'Expiry Date', 'date'), field('document_url', 'Document URL', 'url')]),
  definition('vehicle-fuel-limits', 'Vehicle Fuel Limits', 'Manage vehicle fuel consumption limits.', [...identity('Fuel Limit', 'Limit Reference'), ...vehicle, field('daily_limit', 'Daily Limit', 'currency'), field('monthly_limit', 'Monthly Limit', 'currency'), field('quantity_limit', 'Quantity Limit', 'number'), field('effective_date', 'Effective Date', 'date')]),
  definition('vehicle-allocations', 'Vehicle Allocations', 'Manage vehicle assignments to accounts and operations.', [...identity('Allocation', 'Allocation Reference'), ...vehicle, field('account_id', 'Account ID', 'number'), field('driver_id', 'Driver ID', 'number'), field('start_date', 'Start Date', 'date'), field('end_date', 'End Date', 'date')]),
  definition('vehicle-transactions', 'Vehicle Transactions', 'Review fuel and account transactions by vehicle.', [...identity('Transaction', 'Transaction Reference'), ...vehicle, field('transaction_date', 'Transaction Date', 'datetime'), field('quantity', 'Quantity', 'number'), field('amount', 'Amount', 'currency'), field('station', 'Station')], { readOnly: true }),
  definition('vehicle-maintenance', 'Vehicle Maintenance', 'Manage preventative and corrective vehicle maintenance.', [...identity('Maintenance Job', 'Job Number'), ...vehicle, field('maintenance_type', 'Maintenance Type', 'text', true), field('scheduled_date', 'Scheduled Date', 'date'), field('completed_date', 'Completed Date', 'date'), field('cost', 'Cost', 'currency'), field('notes', 'Notes', 'textarea')]),
  definition('vehicle-inspections', 'Vehicle Inspections', 'Record vehicle safety and compliance inspections.', [...identity('Inspection', 'Inspection Number'), ...vehicle, field('inspection_type', 'Inspection Type', 'text', true), field('inspection_date', 'Inspection Date', 'date', true), field('result', 'Result'), field('inspector', 'Inspector'), field('notes', 'Notes', 'textarea')]),
  definition('vehicle-tracking', 'Vehicle Tracking', 'Monitor vehicle location and movement.', [...identity('Vehicle', 'Tracking Reference'), ...vehicle, field('current_location', 'Current Location'), field('speed', 'Speed', 'number'), field('last_updated', 'Last Updated', 'datetime')], { readOnly: true }),
  definition('all-drivers', 'All Drivers', 'Manage drivers authorized for fleet operations.', driverFields),
  definition('driver-documents', 'Driver Documents', 'Manage driver identity and employment documents.', [...identity('Document Name', 'Document Number'), ...driver, field('document_type', 'Document Type', 'text', true), field('issue_date', 'Issue Date', 'date'), field('expiry_date', 'Expiry Date', 'date'), field('document_url', 'Document URL', 'url')]),
  definition('driver-licences', 'Driver Licences', 'Manage driving licences and endorsements.', [...identity('Licence Holder', 'Licence Number'), ...driver, field('licence_class', 'Licence Class', 'text', true), field('issue_date', 'Issue Date', 'date'), field('expiry_date', 'Expiry Date', 'date', true), field('issuing_authority', 'Issuing Authority')]),
  definition('driver-assignments', 'Driver Assignments', 'Manage driver-to-vehicle assignments.', [...identity('Assignment', 'Assignment Reference'), ...driver, ...vehicle, field('start_date', 'Start Date', 'date', true), field('end_date', 'End Date', 'date')]),
  definition('driver-fuel-limits', 'Driver Fuel Limits', 'Manage fuel limits assigned to drivers.', [...identity('Driver Limit', 'Limit Reference'), ...driver, field('daily_limit', 'Daily Limit', 'currency'), field('monthly_limit', 'Monthly Limit', 'currency'), field('quantity_limit', 'Quantity Limit', 'number'), field('effective_date', 'Effective Date', 'date')]),
  definition('driver-restrictions', 'Driver Restrictions', 'Manage product, station, time, and vehicle restrictions.', [...identity('Restriction', 'Restriction Reference'), ...driver, field('restriction_type', 'Restriction Type', 'text', true), field('restriction_value', 'Restriction Value', 'text', true), field('start_date', 'Start Date', 'date'), field('end_date', 'End Date', 'date'), field('reason', 'Reason', 'textarea')]),
  definition('driver-pin-management', 'Driver PIN Management', 'Manage secure driver PIN issuance and reset records.', [...identity('PIN Record', 'PIN Reference'), ...driver, field('pin_status', 'PIN Status'), field('issued_date', 'Issued Date', 'datetime'), field('expires_at', 'Expires At', 'datetime'), field('reset_required', 'Reset Required')]),
  definition('driver-performance', 'Driver Performance', 'Review driver safety, delivery, and fuel-efficiency performance.', [...identity('Driver', 'Performance Reference'), ...driver, field('period', 'Period'), field('deliveries_completed', 'Deliveries Completed', 'number'), field('fuel_efficiency', 'Fuel Efficiency', 'number'), field('safety_score', 'Safety Score', 'number'), field('overall_score', 'Overall Score', 'number')], { readOnly: true }),
]

export const fleetConfigs = definitions.map(createFuelOperationPage)
export const fleetPageRegistry = Object.fromEntries(fleetConfigs.map((page) => [page.id, page]))
