"""add generic menu resources

Revision ID: 2c11a29ab433
Revises: 45b65c0dad69
Create Date: 2026-08-09 14:46:44.366955
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2c11a29ab433'
down_revision: Union[str, Sequence[str], None] = '45b65c0dad69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generic_records',
    sa.Column('resource_path', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_path', 'code', name='uq_generic_resource_code')
    )
    op.create_index(op.f('ix_generic_records_code'), 'generic_records', ['code'], unique=False)
    op.create_index(op.f('ix_generic_records_deleted_at'), 'generic_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generic_records_name'), 'generic_records', ['name'], unique=False)
    op.create_index(op.f('ix_generic_records_resource_path'), 'generic_records', ['resource_path'], unique=False)
    op.create_index(op.f('ix_generic_records_status'), 'generic_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generic_records_status'), table_name='generic_records')
    op.drop_index(op.f('ix_generic_records_resource_path'), table_name='generic_records')
    op.drop_index(op.f('ix_generic_records_name'), table_name='generic_records')
    op.drop_index(op.f('ix_generic_records_deleted_at'), table_name='generic_records')
    op.drop_index(op.f('ix_generic_records_code'), table_name='generic_records')
    op.drop_table('generic_records')
    # ### end Alembic commands ###
