"""initial fms schema

Revision ID: 45b65c0dad69
Revises: 
Create Date: 2026-08-09 13:46:15.585501
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '45b65c0dad69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('accounts',
    sa.Column('account_number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_deleted_at'), 'accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_verification_status'), 'accounts', ['verification_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('banks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_code'), 'banks', ['code'], unique=True)
    op.create_index(op.f('ix_banks_country'), 'banks', ['country'], unique=False)
    op.create_index(op.f('ix_banks_deleted_at'), 'banks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_banks_name'), 'banks', ['name'], unique=False)
    op.create_index(op.f('ix_banks_status'), 'banks', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('station_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_types_code'), 'station_types', ['code'], unique=True)
    op.create_index(op.f('ix_station_types_deleted_at'), 'station_types', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_types_name'), 'station_types', ['name'], unique=False)
    op.create_index(op.f('ix_station_types_status'), 'station_types', ['status'], unique=False)
    op.create_table('test_items',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_items_deleted_at'), 'test_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_test_items_name'), 'test_items', ['name'], unique=False)
    op.create_index(op.f('ix_test_items_status'), 'test_items', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('station_groups',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('oil_marketing_company_id', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oil_marketing_company_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_groups_code'), 'station_groups', ['code'], unique=True)
    op.create_index(op.f('ix_station_groups_deleted_at'), 'station_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_groups_name'), 'station_groups', ['name'], unique=False)
    op.create_index(op.f('ix_station_groups_oil_marketing_company_id'), 'station_groups', ['oil_marketing_company_id'], unique=False)
    op.create_index(op.f('ix_station_groups_status'), 'station_groups', ['status'], unique=False)
    op.create_table('stations',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('station_type_id', sa.Integer(), nullable=True),
    sa.Column('station_group_id', sa.Integer(), nullable=True),
    sa.Column('oil_marketing_company_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['oil_marketing_company_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['station_group_id'], ['station_groups.id'], ),
    sa.ForeignKeyConstraint(['station_type_id'], ['station_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_deleted_at'), 'stations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stations_district_id'), 'stations', ['district_id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_index(op.f('ix_stations_oil_marketing_company_id'), 'stations', ['oil_marketing_company_id'], unique=False)
    op.create_index(op.f('ix_stations_province_id'), 'stations', ['province_id'], unique=False)
    op.create_index(op.f('ix_stations_station_group_id'), 'stations', ['station_group_id'], unique=False)
    op.create_index(op.f('ix_stations_station_type_id'), 'stations', ['station_type_id'], unique=False)
    op.create_index(op.f('ix_stations_status'), 'stations', ['status'], unique=False)
    op.create_table('station_documents',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('issued_by', sa.String(length=160), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file', sa.String(length=500), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_documents_deleted_at'), 'station_documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_documents_document_name'), 'station_documents', ['document_name'], unique=False)
    op.create_index(op.f('ix_station_documents_document_number'), 'station_documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_station_documents_document_type'), 'station_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_station_documents_expiry_date'), 'station_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_station_documents_station_id'), 'station_documents', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_documents_status'), 'station_documents', ['status'], unique=False)
    op.create_index(op.f('ix_station_documents_verification_status'), 'station_documents', ['verification_status'], unique=False)
    op.create_table('station_inspections',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=80), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('inspector_name', sa.String(length=160), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_inspections_deleted_at'), 'station_inspections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_inspections_inspection_date'), 'station_inspections', ['inspection_date'], unique=False)
    op.create_index(op.f('ix_station_inspections_inspection_type'), 'station_inspections', ['inspection_type'], unique=False)
    op.create_index(op.f('ix_station_inspections_result'), 'station_inspections', ['result'], unique=False)
    op.create_index(op.f('ix_station_inspections_station_id'), 'station_inspections', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_inspections_status'), 'station_inspections', ['status'], unique=False)
    op.create_table('station_performance',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('sales_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_performance_deleted_at'), 'station_performance', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_performance_period'), 'station_performance', ['period'], unique=False)
    op.create_index(op.f('ix_station_performance_station_id'), 'station_performance', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_performance_status'), 'station_performance', ['status'], unique=False)
    op.create_table('station_price_boards',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_price_boards_deleted_at'), 'station_price_boards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_station_price_boards_product_id'), 'station_price_boards', ['product_id'], unique=False)
    op.create_index(op.f('ix_station_price_boards_station_id'), 'station_price_boards', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_price_boards_status'), 'station_price_boards', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_price_boards_status'), table_name='station_price_boards')
    op.drop_index(op.f('ix_station_price_boards_station_id'), table_name='station_price_boards')
    op.drop_index(op.f('ix_station_price_boards_product_id'), table_name='station_price_boards')
    op.drop_index(op.f('ix_station_price_boards_deleted_at'), table_name='station_price_boards')
    op.drop_table('station_price_boards')
    op.drop_index(op.f('ix_station_performance_status'), table_name='station_performance')
    op.drop_index(op.f('ix_station_performance_station_id'), table_name='station_performance')
    op.drop_index(op.f('ix_station_performance_period'), table_name='station_performance')
    op.drop_index(op.f('ix_station_performance_deleted_at'), table_name='station_performance')
    op.drop_table('station_performance')
    op.drop_index(op.f('ix_station_inspections_status'), table_name='station_inspections')
    op.drop_index(op.f('ix_station_inspections_station_id'), table_name='station_inspections')
    op.drop_index(op.f('ix_station_inspections_result'), table_name='station_inspections')
    op.drop_index(op.f('ix_station_inspections_inspection_type'), table_name='station_inspections')
    op.drop_index(op.f('ix_station_inspections_inspection_date'), table_name='station_inspections')
    op.drop_index(op.f('ix_station_inspections_deleted_at'), table_name='station_inspections')
    op.drop_table('station_inspections')
    op.drop_index(op.f('ix_station_documents_verification_status'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_status'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_station_id'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_expiry_date'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_document_type'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_document_number'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_document_name'), table_name='station_documents')
    op.drop_index(op.f('ix_station_documents_deleted_at'), table_name='station_documents')
    op.drop_table('station_documents')
    op.drop_index(op.f('ix_stations_status'), table_name='stations')
    op.drop_index(op.f('ix_stations_station_type_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_station_group_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_province_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_oil_marketing_company_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_district_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_deleted_at'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_station_groups_status'), table_name='station_groups')
    op.drop_index(op.f('ix_station_groups_oil_marketing_company_id'), table_name='station_groups')
    op.drop_index(op.f('ix_station_groups_name'), table_name='station_groups')
    op.drop_index(op.f('ix_station_groups_deleted_at'), table_name='station_groups')
    op.drop_index(op.f('ix_station_groups_code'), table_name='station_groups')
    op.drop_table('station_groups')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_test_items_status'), table_name='test_items')
    op.drop_index(op.f('ix_test_items_name'), table_name='test_items')
    op.drop_index(op.f('ix_test_items_deleted_at'), table_name='test_items')
    op.drop_table('test_items')
    op.drop_index(op.f('ix_station_types_status'), table_name='station_types')
    op.drop_index(op.f('ix_station_types_name'), table_name='station_types')
    op.drop_index(op.f('ix_station_types_deleted_at'), table_name='station_types')
    op.drop_index(op.f('ix_station_types_code'), table_name='station_types')
    op.drop_table('station_types')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_banks_status'), table_name='banks')
    op.drop_index(op.f('ix_banks_name'), table_name='banks')
    op.drop_index(op.f('ix_banks_deleted_at'), table_name='banks')
    op.drop_index(op.f('ix_banks_country'), table_name='banks')
    op.drop_index(op.f('ix_banks_code'), table_name='banks')
    op.drop_table('banks')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_accounts_verification_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_deleted_at'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
