"""preserve station configuration fields

Revision ID: e0c1ac7c24af
Revises: 2c11a29ab433
Create Date: 2026-08-09 14:49:51.782974
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e0c1ac7c24af'
down_revision: Union[str, Sequence[str], None] = '2c11a29ab433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    details = sa.Column('details', sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
    op.add_column('station_documents', details)
    with op.batch_alter_table('station_documents') as batch:
        batch.alter_column('file', existing_type=sa.VARCHAR(length=500), type_=sa.Text(), existing_nullable=False)
    for table in ('station_groups', 'station_inspections', 'station_performance', 'station_price_boards', 'station_types', 'stations'):
        op.add_column(table, sa.Column('details', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'details')
    op.drop_column('station_types', 'details')
    op.drop_column('station_price_boards', 'details')
    op.drop_column('station_performance', 'details')
    op.drop_column('station_inspections', 'details')
    op.drop_column('station_groups', 'details')
    with op.batch_alter_table('station_documents') as batch:
        batch.alter_column('file', existing_type=sa.Text(), type_=sa.VARCHAR(length=500), existing_nullable=False)
    op.drop_column('station_documents', 'details')
    # ### end Alembic commands ###
