import { pageConfigSchema } from '@/framework/schemas/page.schema'
import { validateConfig } from '@/framework/schemas/validation'

import type {
    ApiConfig,
    FormConfig,
    ListPageConfig,
    PageConfig,
} from '@/types/configuration.types'

const api: ApiConfig = {
    baseUrl: '/api',
    data_mapping: {
        type: 'paginated',
        items: 'data.items',
        total: 'data.total',
        page: 'data.page',
        pageSize: 'data.pageSize',
    },
    endpoints: {
        list: { path: '/accounts/ngos', method: 'GET' },
        item: {
            path: '/accounts/ngos/{id}',
            method: 'GET',
            responseMappingPath: 'data',
        },
        create: {
            path: '/accounts/ngos',
            method: 'POST',
            responseMappingPath: 'data',
        },
        update: {
            path: '/accounts/ngos/{id}',
            method: 'PUT',
            responseMappingPath: 'data',
        },
        delete: {
            path: '/accounts/ngos/{id}',
            method: 'DELETE',
        },
    },
}
// const cardsApi: ApiConfig = {
//     baseUrl: '/api',
//     data_mapping: {
//         type: 'paginated',
//         items: 'data.items',
//         total: 'data.total',
//         page: 'data.page',
//         pageSize: 'data.pageSize',
//     },
//     endpoints: {
//         list: {
//             path: '/accounts/ngos/{id}/cards',
//             method: 'GET',
//         },
//     },
// }
const vehiclesApi: ApiConfig = {
    baseUrl: '/api',
    data_mapping: {
        type: 'paginated',
        items: 'data.items',
        total: 'data.total',
        page: 'data.page',
        pageSize: 'data.pageSize',
    },
    endpoints: {
        list: {
            path: '/accounts/ngos/{id}/vehicles',
            method: 'GET',
        },
    },
}

const transactionsApi: ApiConfig = {
    baseUrl: '/api',
    data_mapping: {
        type: 'paginated',
        items: 'data.items',
        total: 'data.total',
        page: 'data.page',
        pageSize: 'data.pageSize',
    },
    endpoints: {
        list: {
            path: '/accounts/ngos/{id}/transactions',
            method: 'GET',
        },
    },
}

const form: FormConfig = {
    cancelPath: '/accounts/ngos',
    resetEnabled: true,
    layout: {
        type: 'columns',
        columns: 3,
    },
    fields: [
        {
            name: 'name',
            type: 'text',
            label: 'NGO Name',
            required: true,
        },
        {
            name: 'code',
            type: 'text',
            label: 'NGO Code',
            required: true,
        },
        {
            name: 'registration_number',
            type: 'text',
            label: 'Registration Number',
            required: true,
        },
        {
            name: 'tpin',
            type: 'text',
            label: 'TPIN',
        },
        {
            name: 'ngo_type',
            type: 'select',
            label: 'NGO Type',
            required: true,
            options: [
                { label: 'Local NGO', value: 'local' },
                { label: 'International NGO', value: 'international' },
                { label: 'Foundation', value: 'foundation' },
                { label: 'Charity', value: 'charity' },
                { label: 'Faith Based Organization', value: 'faith_based' },
            ],
        },
        {
            name: 'sector',
            type: 'select',
            label: 'Primary Sector',
            required: true,
            options: [
                { label: 'Health', value: 'health' },
                { label: 'Education', value: 'education' },
                { label: 'Agriculture', value: 'agriculture' },
                { label: 'Environment', value: 'environment' },
                { label: 'Humanitarian', value: 'humanitarian' },
                { label: 'Community Development', value: 'community_development' },
                { label: 'Other', value: 'other' },
            ],
        },
        {
            name: 'funding_organization',
            type: 'text',
            label: 'Primary Funding Organization',
        },
        {
            name: 'email',
            type: 'email',
            label: 'Email',
            required: true,
        },
        {
            name: 'phone',
            type: 'text',
            label: 'Phone',
            required: true,
        },
        {
            name: 'contact_person',
            type: 'text',
            label: 'Contact Person',
            required: true,
        },
        {
            name: 'contact_person_phone',
            type: 'text',
            label: 'Contact Person Phone',
            required: true,
        },
        {
            name: 'province',
            type: 'text',
            label: 'Province',
            required: true,
        },
        {
            name: 'district',
            type: 'text',
            label: 'District',
            required: true,
        },
        {
            name: 'address',
            type: 'textarea',
            label: 'Physical Address',
            rows: 4,
            required: true,
        },
        {
            name: 'account_number',
            type: 'text',
            label: 'Account Number',
        },
        {
            name: 'credit_limit',
            type: 'number',
            label: 'Credit Limit',
            default_value: 0,
        },
        {
            name: 'verification_status',
            type: 'select',
            label: 'Verification Status',
            default_value: 'pending',
            options: [
                { label: 'Pending', value: 'pending' },
                { label: 'Verified', value: 'verified' },
                { label: 'Rejected', value: 'rejected' },
            ],
        },
        {
            name: 'status',
            type: 'select',
            label: 'Status',
            required: true,
            default_value: 'pending',
            options: [
                { label: 'Pending', value: 'pending' },
                { label: 'Active', value: 'active' },
                { label: 'Inactive', value: 'inactive' },
                { label: 'Suspended', value: 'suspended' },
            ],
        },
    ],
}

const raw: PageConfig = {
    id: 'ngos',
    title: 'NGOs',
    page_title: 'Non-Governmental Organizations',
    description: 'Manage NGO fuel accounts and allocations.',
    type: 'list',
    page_type: 'list',
    path: '/accounts/ngos',
    route: '/accounts/ngos',
    api,

    statistics: [
        {
            id: 'total',
            type: 'statistic',
            title: 'Total NGOs',
            dataPath: 'statistics.total',
            icon: 'HeartHandshake',
            format: 'number',
        },
        {
            id: 'active',
            type: 'statistic',
            title: 'Active',
            dataPath: 'statistics.active',
            icon: 'CircleCheck',
            format: 'number',
        },
        {
            id: 'pending',
            type: 'statistic',
            title: 'Pending',
            dataPath: 'statistics.pending',
            icon: 'Clock',
            format: 'number',
        },
        {
            id: 'suspended',
            type: 'statistic',
            title: 'Suspended',
            dataPath: 'statistics.suspended',
            icon: 'Ban',
            format: 'number',
        },
    ],

    filters: [
        {
            id: 'search',
            type: 'search',
            label: 'Search',
            field: 'search',
            query_parameter: 'search',
            placeholder: 'Search NGO name, account number or registration',
        },
        {
            id: 'ngo-type',
            type: 'select',
            label: 'NGO Type',
            field: 'ngo_type',
            query_parameter: 'ngo_type',
            options: [
                { label: 'Local', value: 'local' },
                { label: 'International', value: 'international' },
                { label: 'Foundation', value: 'foundation' },
                { label: 'Charity', value: 'charity' },
            ],
        },
        {
            id: 'status',
            type: 'select',
            label: 'Status',
            field: 'status',
            query_parameter: 'status',
            options: [
                { label: 'Pending', value: 'pending' },
                { label: 'Active', value: 'active' },
                { label: 'Suspended', value: 'suspended' },
            ],
        },
    ],

    table: {
        rowKey: 'id',
        stickyHeader: true,
        striped: true,
        pagination: {
            enabled: true,
            pageSize: 10,
            pageSizeOptions: [10, 20, 50],
        },
        sorting: {
            enabled: true,
            defaultColumn: 'name',
            defaultDirection: 'asc',
        },
        columns: [
            {
                id: 'account-number',
                type: 'text',
                header: 'Account No.',
                accessor: 'account_number',
            },
            {
                id: 'code',
                type: 'text',
                header: 'Code',
                accessor: 'code',
                sortable: true,
            },
            {
                id: 'name',
                type: 'text',
                header: 'NGO',
                accessor: 'name',
                searchable: true,
                sortable: true,
            },
            {
                id: 'ngo-type',
                type: 'text',
                header: 'Type',
                accessor: 'ngo_type',
            },
            {
                id: 'sector',
                type: 'text',
                header: 'Sector',
                accessor: 'sector',
            },
            {
                id: 'province',
                type: 'text',
                header: 'Province',
                accessor: 'province',
            },
            {
                id: 'vehicles',
                type: 'number',
                header: 'Vehicles',
                accessor: 'total_vehicles',
            },
            {
                id: 'balance',
                type: 'number',
                header: 'Balance',
                accessor: 'account_balance',
            },
            {
                id: 'verification',
                type: 'badge',
                header: 'Verification',
                accessor: 'verification_status',
                options: {
                    verified: 'success',
                    pending: 'warning',
                    rejected: 'danger',
                },
            },
            {
                id: 'status',
                type: 'badge',
                header: 'Status',
                accessor: 'status',
                options: {
                    active: 'success',
                    pending: 'warning',
                    inactive: 'warning',
                    suspended: 'danger',
                },
            },
            {
                id: 'actions',
                type: 'actions',
                header: 'Actions',
                actions: [
                    {
                        id: 'view',
                        type: 'navigate',
                        label: 'View',
                        icon: 'Eye',
                        path: '/accounts/ngos/{id}',
                    },
                    {
                        id: 'edit',
                        type: 'edit',
                        label: 'Edit',
                        icon: 'Pencil',
                        path: '/accounts/ngos/{id}/edit',
                    },
                    //  {
                    //     id: 'cards',
                    //     type: 'navigate',
                    //     label: 'Cards',
                    //     icon: 'atm',
                    //     path: '/accounts/ngos/{id}/cards',
                    // },
                    {
                        id: 'vehicles',
                        type: 'navigate',
                        label: 'Vehicles',
                        icon: 'Truck',
                        path: '/accounts/ngos/{id}/vehicles',
                    },
                    {
                        id: 'transactions',
                        type: 'navigate',
                        label: 'Transactions',
                        icon: 'Receipt',
                        path: '/accounts/ngos/{id}/transactions',
                    },
                    {
                        id: 'delete',
                        type: 'delete',
                        label: 'Delete',
                        icon: 'Trash2',
                        endpoint: '/api/accounts/ngos/{id}',
                        requires_confirmation: true,
                        confirmation: 'Delete this NGO?',
                        success_message: 'NGO deleted.',
                    },
                ],
            },
        ],
    },

    page_actions: [
        {
            id: 'add',
            type: 'navigate',
            label: 'Add NGO',
            icon: 'Plus',
            path: '/accounts/ngos/create',
        },
    ],

    sub_pages: [
        {
            id: 'ngos-create',
            parentId: 'ngos',
            title: 'Add NGO',
            page_title: 'Add NGO',
            type: 'create',
            page_type: 'create',
            path: '/accounts/ngos/create',
            route: '/accounts/ngos/create',
            api,
            form: {
                ...form,
                submitLabel: 'Add NGO',
            },
            page_actions: [
                {
                    id: 'back',
                    type: 'navigate',
                    label: 'Back to NGOs',
                    path: '/accounts/ngos',
                    icon: 'ArrowLeft',
                    variant: 'secondary',
                },
            ],
        },
        {
            id: 'ngos-details',
            parentId: 'ngos',
            title: 'NGO Details',
            page_title: 'NGO Details',
            type: 'details',
            page_type: 'details',
            path: '/accounts/ngos/:id',
            route: '/accounts/ngos/:id',
            api,
            recordIdParam: 'id',
            fields: [
                'name',
                'code',
                'account_number',
                'registration_number',
                'ngo_type',
                'sector',
                'funding_organization',
                'email',
                'phone',
                'province',
                'district',
                'address',
                'account_balance',
                'verification_status',
                'status',
            ],

            sections: [
                {
                    id: 'overview',
                    title: 'NGO Information',
                    fields: [
                        { key: 'name', label: 'NGO Name', type: 'text' },
                        { key: 'code', label: 'Code', type: 'text' },
                        { key: 'registration_number', label: 'Registration Number', type: 'text' },
                        { key: 'ngo_type', label: 'NGO Type', type: 'text' },
                        { key: 'sector', label: 'Sector', type: 'text' },
                        { key: 'funding_organization', label: 'Funding Organization', type: 'text' },
                    ],
                },
                {
                    id: 'account',
                    title: 'Account',
                    fields: [
                        { key: 'account_number', label: 'Account Number', type: 'text' },
                        { key: 'account_balance', label: 'Balance', type: 'number' },
                        { key: 'credit_limit', label: 'Credit Limit', type: 'number' },
                    ],
                },
            ],
            page_actions: [
                {
                    id: 'back',
                    type: 'navigate',
                    label: 'Back to NGOs',
                    path: '/accounts/ngos',
                    icon: 'ArrowLeft',
                    variant: 'secondary',
                },
            ],
        },
        {
            id: 'ngos-edit',
            parentId: 'ngos',
            title: 'Edit NGO',
            page_title: 'Edit NGO',
            type: 'edit',
            page_type: 'edit',
            path: '/accounts/ngos/:id/edit',
            route: '/accounts/ngos/:id/edit',
            api,
            form: {
                ...form,
                submitLabel: 'Save Changes',
            },
            recordIdParam: 'id',
        },        
        {
            id: 'ngos-vehicles',
            parentId: 'ngos',
            title: 'NGOs Vehicles',
            page_title: 'Registered Vehicles',
            description: 'View vehicles registered to this NGO account.',
            type: 'list',
            page_type: 'list',
            path: '/accounts/ngos/:id/vehicles',
            route: '/accounts/ngos/:id/vehicles',
            api: vehiclesApi,
            statistics: [
                {
                    id: 'total-vehicles',
                    type: 'statistic',
                    title: 'Total Vehicles',
                    dataPath: 'statistics.total',
                    icon: 'Car',
                    format: 'number',
                },
                {
                    id: 'active-vehicles',
                    type: 'statistic',
                    title: 'Active',
                    dataPath: 'statistics.active',
                    icon: 'CircleCheck',
                    format: 'number',
                },
                {
                    id: 'inactive-vehicles',
                    type: 'statistic',
                    title: 'Inactive',
                    dataPath: 'statistics.inactive',
                    icon: 'CircleX',
                    format: 'number',
                },
                {
                    id: 'fuel-cards',
                    type: 'statistic',
                    title: 'Assigned Fuel Cards',
                    dataPath: 'statistics.assigned_cards',
                    icon: 'CreditCard',
                    format: 'number',
                },
            ],
            page_actions: [
                {
                    id: 'back',
                    type: 'navigate',
                    label: 'Back to NGOs',
                    path: '/accounts/ngos',
                    icon: 'ArrowLeft',
                    variant: 'secondary',
                },
            ],
            filters: [
                {
                    id: 'search',
                    type: 'search',
                    label: 'Search',
                    field: 'search',
                    query_parameter: 'search',
                    placeholder: 'Search registration, fleet number, make or model',
                },
                {
                    id: 'fuel-type',
                    type: 'select',
                    label: 'Fuel Type',
                    field: 'fuel_type',
                    query_parameter: 'fuel_type',
                    options: [
                        { label: 'Petrol', value: 'petrol' },
                        { label: 'Diesel', value: 'diesel' },
                        { label: 'Electric', value: 'electric' },
                        { label: 'Hybrid', value: 'hybrid' },
                    ],
                },
                {
                    id: 'status',
                    type: 'select',
                    label: 'Status',
                    field: 'status',
                    query_parameter: 'status',
                    options: [
                        { label: 'Active', value: 'active' },
                        { label: 'Inactive', value: 'inactive' },
                        { label: 'Suspended', value: 'suspended' },
                    ],
                },
            ],
            table: {
                rowKey: 'id',
                stickyHeader: true,
                striped: true,
                pagination: {
                    enabled: true,
                    pageSize: 10,
                    pageSizeOptions: [10, 20, 50, 100],
                },
                sorting: {
                    enabled: true,
                    defaultColumn: 'registration_number',
                    defaultDirection: 'asc',
                },
                columns: [
                    {
                        id: 'registration-number',
                        type: 'text',
                        header: 'Registration No.',
                        accessor: 'registration_number',
                        sortable: true,
                        searchable: true,
                    },
                    {
                        id: 'fleet-number',
                        type: 'text',
                        header: 'Fleet No.',
                        accessor: 'fleet_number',
                        sortable: true,
                    },
                    {
                        id: 'make',
                        type: 'text',
                        header: 'Make',
                        accessor: 'make',
                        sortable: true,
                    },
                    {
                        id: 'model',
                        type: 'text',
                        header: 'Model',
                        accessor: 'model',
                    },
                    {
                        id: 'fuel-type',
                        type: 'text',
                        header: 'Fuel Type',
                        accessor: 'fuel_type',
                    },
                    {
                        id: 'fuel-card',
                        type: 'text',
                        header: 'Fuel Card',
                        accessor: 'fuel_card.card_number',
                    },
                    {
                        id: 'monthly-limit',
                        type: 'number',
                        header: 'Monthly Limit',
                        accessor: 'monthly_limit',
                        format: 'currency',
                        currency: 'ZMW',
                    },
                    {
                        id: 'status',
                        type: 'badge',
                        header: 'Status',
                        accessor: 'status',
                        sortable: true,
                        options: {
                            active: 'success',
                            inactive: 'warning',
                            suspended: 'danger',
                        },
                    },
                    {
                        id: 'created-at',
                        type: 'datetime',
                        header: 'Created',
                        accessor: 'created_at',
                        sortable: true,
                    },
                ],
            },
        },
        {
            id: 'ngos-transactions',
            parentId: 'ngos',
            title: 'NGO Transactions',
            page_title: 'NGO Transactions',
            description: 'Review fuel and account transactions for this NGO.',
            type: 'list',
            page_type: 'list',
            path: '/accounts/ngos/:id/transactions',
            route: '/accounts/ngos/:id/transactions',
            api: transactionsApi,
            statistics: [
                {
                    id: 'total-transactions',
                    type: 'statistic',
                    title: 'Total Transactions',
                    dataPath: 'statistics.total',
                    icon: 'Receipt',
                    format: 'number',
                },
                {
                    id: 'successful-transactions',
                    type: 'statistic',
                    title: 'Successful',
                    dataPath: 'statistics.successful',
                    icon: 'CircleCheck',
                    format: 'number',
                },
                {
                    id: 'failed-transactions',
                    type: 'statistic',
                    title: 'Failed',
                    dataPath: 'statistics.failed',
                    icon: 'CircleX',
                    format: 'number',
                },
            ],
            page_actions: [
                {
                    id: 'back',
                    type: 'navigate',
                    label: 'Back to NGOs',
                    path: '/accounts/ngos',
                    icon: 'ArrowLeft',
                    variant: 'secondary',
                },
            ],
            filters: [
                {
                    id: 'search',
                    type: 'search',
                    label: 'Search',
                    field: 'search',
                    query_parameter: 'search',
                    placeholder: 'Search reference, vehicle, card or station',
                },
                {
                    id: 'transaction-type',
                    type: 'select',
                    label: 'Transaction Type',
                    field: 'transaction_type',
                    query_parameter: 'transaction_type',
                    options: [
                        { label: 'Fuel Purchase', value: 'fuel_purchase' },
                        { label: 'Payment', value: 'payment' },
                        { label: 'Refund', value: 'refund' },
                        { label: 'Adjustment', value: 'adjustment' },
                    ],
                },
                {
                    id: 'transaction-date',
                    type: 'date_range',
                    label: 'Transaction Date',
                    fromField: 'date_from',
                    toField: 'date_to',
                    from_query_parameter: 'date_from',
                    to_query_parameter: 'date_to',
                },
                {
                    id: 'status',
                    type: 'select',
                    label: 'Status',
                    field: 'status',
                    query_parameter: 'status',
                    options: [
                        { label: 'Successful', value: 'successful' },
                        { label: 'Pending', value: 'pending' },
                        { label: 'Failed', value: 'failed' },
                        { label: 'Reversed', value: 'reversed' },
                    ],
                },
            ],
            table: {
                rowKey: 'id',
                stickyHeader: true,
                striped: true,
                pagination: {
                    enabled: true,
                    pageSize: 10,
                    pageSizeOptions: [10, 20, 50, 100],
                },
                sorting: {
                    enabled: true,
                    defaultColumn: 'transaction_date',
                    defaultDirection: 'desc',
                },
                columns: [
                    {
                        id: 'reference',
                        type: 'text',
                        header: 'Reference',
                        accessor: 'reference',
                        sortable: true,
                        searchable: true,
                    },
                    {
                        id: 'transaction-date',
                        type: 'datetime',
                        header: 'Date',
                        accessor: 'transaction_date',
                        sortable: true,
                    },
                    {
                        id: 'transaction-type',
                        type: 'text',
                        header: 'Type',
                        accessor: 'transaction_type',
                        sortable: true,
                    },
                    {
                        id: 'vehicle',
                        type: 'text',
                        header: 'Vehicle',
                        accessor: 'vehicle.registration_number',
                    },
                    {
                        id: 'station',
                        type: 'text',
                        header: 'Station',
                        accessor: 'station.name',
                    },
                    {
                        id: 'quantity',
                        type: 'number',
                        header: 'Quantity',
                        accessor: 'quantity',
                        sortable: true,
                        format: 'decimal',
                    },
                    {
                        id: 'amount',
                        type: 'number',
                        header: 'Amount',
                        accessor: 'amount',
                        sortable: true,
                        format: 'currency',
                        currency: 'ZMW',
                    },
                    {
                        id: 'status',
                        type: 'badge',
                        header: 'Status',
                        accessor: 'status',
                        sortable: true,
                        options: {
                            successful: 'success',
                            pending: 'warning',
                            failed: 'danger',
                            reversed: 'info',
                        },
                    },
                ],
            },
        },
    ],
}

export const ngosListConfig = validateConfig(
    'NGO list page',
    pageConfigSchema,
    raw,
) as ListPageConfig

export const ngosCreateConfig = validateConfig(
    'NGO create page',
    pageConfigSchema,
    ngosListConfig.sub_pages?.find((page) => page.type === 'create'),
)

export const ngosDetailsConfig = validateConfig(
    'NGO details page',
    pageConfigSchema,
    ngosListConfig.sub_pages?.find((page) => page.type === 'details'),
)

export const ngosEditConfig = validateConfig(
    'NGO edit page',
    pageConfigSchema,
    ngosListConfig.sub_pages?.find((page) => page.type === 'edit'),
)