import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from '@/config/modules/fuel-operation/fuel-operation-page-factory'

const routeRoot = import.meta.env.VITE_API_ROUTE_LOGISTICS || '/logistics'
const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const delivery = [field('delivery_order_id', 'Delivery Order ID', 'number', true), field('vehicle_id', 'Vehicle ID', 'number'), field('driver_id', 'Driver ID', 'number'), field('scheduled_date', 'Scheduled Date', 'date'), field('quantity', 'Quantity', 'number')]
const location = [field('address', 'Address', 'textarea'), field('province', 'Province'), field('district', 'District'), field('latitude', 'Latitude', 'number'), field('longitude', 'Longitude', 'number')]
const definition = (slug: string, title: string, description: string, fields: FuelOperationField[], options: Partial<FuelOperationDefinition> = {}): FuelOperationDefinition => ({ slug, title, description, fields, routeRoot, idPrefix: 'logistics', icon: 'Circle', ...options })

const definitions: FuelOperationDefinition[] = [
  definition('logistics-dashboard', 'Logistics Dashboard', 'Review logistics workload, delivery performance, and exceptions.', [...identity('Metric', 'Metric Code'), field('total_deliveries', 'Total Deliveries', 'number'), field('active_deliveries', 'Active Deliveries', 'number'), field('completed_deliveries', 'Completed Deliveries', 'number'), field('exception_count', 'Exceptions', 'number')], { readOnly: true }),
  definition('depots', 'Depots', 'Manage fuel distribution depots.', [...identity('Depot Name', 'Depot Code'), ...location, field('capacity', 'Capacity', 'number'), field('manager_name', 'Manager')]),
  definition('warehouses', 'Warehouses', 'Manage logistics warehouses and storage facilities.', [...identity('Warehouse Name', 'Warehouse Code'), field('depot_id', 'Depot ID', 'number'), ...location, field('capacity', 'Capacity', 'number')]),
  definition('delivery-requests', 'Delivery Requests', 'Manage requests for fuel delivery.', [...identity('Request Name', 'Request Number'), field('account_id', 'Account ID', 'number', true), field('station_id', 'Station ID', 'number'), field('product_id', 'Fuel Product ID', 'number', true), field('quantity', 'Requested Quantity', 'number', true), field('required_date', 'Required Date', 'date')]),
  definition('delivery-orders', 'Delivery Orders', 'Manage confirmed fuel delivery orders.', [...identity('Order Name', 'Order Number'), field('delivery_request_id', 'Delivery Request ID', 'number'), ...delivery, field('dispatch_date', 'Dispatch Date', 'datetime')]),
  definition('dispatch-planning', 'Dispatch Planning', 'Plan vehicles, drivers, routes, and loading windows.', [...identity('Dispatch Plan', 'Plan Number'), ...delivery, field('route_id', 'Route ID', 'number'), field('loading_time', 'Loading Time', 'datetime')]),
  definition('delivery-schedule', 'Delivery Schedule', 'Review scheduled fuel deliveries.', [...identity('Delivery', 'Delivery Number'), ...delivery, field('destination', 'Destination'), field('estimated_arrival', 'Estimated Arrival', 'datetime')], { readOnly: true }),
  definition('active-deliveries', 'Active Deliveries', 'Monitor deliveries currently in progress.', [...identity('Delivery', 'Delivery Number'), ...delivery, field('current_location', 'Current Location'), field('estimated_arrival', 'Estimated Arrival', 'datetime')], { readOnly: true }),
  definition('delivery-routes', 'Delivery Routes', 'Manage approved delivery routes.', [...identity('Route Name', 'Route Code'), field('origin', 'Origin', 'text', true), field('destination', 'Destination', 'text', true), field('distance', 'Distance', 'number'), field('estimated_duration', 'Estimated Duration'), field('waypoints', 'Waypoints', 'textarea')]),
  definition('tanker-trucks', 'Tanker Trucks', 'Manage tanker trucks assigned to fuel deliveries.', [...identity('Truck Name', 'Registration Number'), field('vehicle_id', 'Vehicle ID', 'number'), field('capacity', 'Tank Capacity', 'number', true), field('compartments', 'Compartments', 'number'), field('current_driver_id', 'Current Driver ID', 'number')]),
  definition('delivery-drivers', 'Delivery Drivers', 'Manage drivers assigned to delivery operations.', [...identity('Driver Name', 'Employee Number'), field('phone', 'Phone'), field('licence_number', 'Licence Number', 'text', true), field('licence_expiry', 'Licence Expiry', 'date'), field('current_vehicle_id', 'Current Vehicle ID', 'number')]),
  definition('loading-records', 'Loading Records', 'Record fuel loaded for dispatch.', [...identity('Loading Record', 'Loading Number'), ...delivery, field('depot_id', 'Depot ID', 'number'), field('loaded_quantity', 'Loaded Quantity', 'number', true), field('loading_date', 'Loading Date', 'datetime', true), field('seal_number', 'Seal Number')]),
  definition('offloading-records', 'Offloading Records', 'Record fuel received and offloaded at destinations.', [...identity('Offloading Record', 'Offloading Number'), ...delivery, field('received_quantity', 'Received Quantity', 'number', true), field('offloading_date', 'Offloading Date', 'datetime', true), field('received_by', 'Received By')]),
  definition('delivery-tracking', 'Delivery Tracking', 'Track live and recent delivery movement.', [...identity('Delivery', 'Tracking Number'), ...delivery, field('current_location', 'Current Location'), field('last_updated', 'Last Updated', 'datetime'), field('estimated_arrival', 'Estimated Arrival', 'datetime')], { readOnly: true }),
  definition('proof-of-delivery', 'Proof of Delivery', 'Capture delivery acceptance and supporting evidence.', [...identity('Proof of Delivery', 'POD Number'), ...delivery, field('delivered_quantity', 'Delivered Quantity', 'number', true), field('received_by', 'Received By', 'text', true), field('delivery_date', 'Delivery Date', 'datetime', true), field('document_url', 'Document URL', 'url')]),
  definition('delivery-exceptions', 'Delivery Exceptions', 'Record and resolve delivery incidents and variances.', [...identity('Exception', 'Exception Number'), ...delivery, field('exception_type', 'Exception Type', 'text', true), field('reported_date', 'Reported Date', 'datetime'), field('description', 'Description', 'textarea', true), field('resolution', 'Resolution', 'textarea')]),
  definition('failed-deliveries', 'Failed Deliveries', 'Review unsuccessful deliveries and failure reasons.', [...identity('Delivery', 'Delivery Number'), ...delivery, field('failure_reason', 'Failure Reason', 'textarea'), field('failed_date', 'Failed Date', 'datetime')], { readOnly: true }),
  definition('completed-deliveries', 'Completed Deliveries', 'Review successfully completed deliveries.', [...identity('Delivery', 'Delivery Number'), ...delivery, field('delivered_quantity', 'Delivered Quantity', 'number'), field('completed_date', 'Completed Date', 'datetime'), field('received_by', 'Received By')], { readOnly: true }),
  definition('delivery-reconciliation', 'Delivery Reconciliation', 'Compare ordered, loaded, and delivered fuel quantities.', [...identity('Reconciliation', 'Reconciliation Number'), ...delivery, field('ordered_quantity', 'Ordered Quantity', 'number'), field('loaded_quantity', 'Loaded Quantity', 'number'), field('delivered_quantity', 'Delivered Quantity', 'number'), field('variance', 'Variance', 'number'), field('reconciliation_date', 'Date', 'date')], { readOnly: true }),
]

export const logisticsConfigs = definitions.map(createFuelOperationPage)
export const logisticsPageRegistry = Object.fromEntries(logisticsConfigs.map((page) => [page.id, page]))
