import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from '@/config/modules/fuel-operation/fuel-operation-page-factory'

const routeRoot = import.meta.env.VITE_API_ROUTE_MY_ACCOUNT || '/my-account'
const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const financial = [field('transaction_date', 'Transaction Date', 'datetime'), field('amount', 'Amount', 'currency'), field('balance', 'Balance', 'currency'), field('payment_method', 'Payment Method')]
const def = (slug: string, title: string, description: string, fields: FuelOperationField[], readOnly = false): FuelOperationDefinition => ({ slug, title, description, fields, routeRoot, idPrefix: 'my-account', icon: 'Circle', readOnly })

const definitions: FuelOperationDefinition[] = [
  def('my-dashboard', 'My Dashboard', 'Review personal account activity, balances, requests, and alerts.', [...identity('Dashboard Metric', 'Metric Code'), field('account_balance', 'Account Balance', 'currency'), field('active_vehicles', 'Active Vehicles', 'number'), field('active_cards', 'Active Cards', 'number'), field('pending_requests', 'Pending Requests', 'number')], true),
  def('my-profile', 'My Profile', 'Review and update personal profile information.', [...identity('Full Name', 'User Reference'), field('email', 'Email', 'email', true), field('phone', 'Phone'), field('job_title', 'Job Title'), field('department', 'Department'), field('preferred_language', 'Preferred Language')]),
  def('my-organization', 'My Organization', 'Review organization and account information.', [...identity('Organization Name', 'Organization Code'), field('account_number', 'Account Number'), field('organization_type', 'Organization Type'), field('registration_number', 'Registration Number'), field('address', 'Address', 'textarea'), field('account_balance', 'Account Balance', 'currency')], true),
  def('my-vehicles', 'My Vehicles', 'Manage vehicles associated with the current account.', [...identity('Vehicle', 'Registration Number'), field('make', 'Make'), field('model', 'Model'), field('year', 'Year', 'number'), field('fuel_type', 'Fuel Type'), field('monthly_limit', 'Monthly Limit', 'currency')]),
  def('my-drivers', 'My Drivers', 'Manage drivers associated with the current account.', [...identity('Driver Name', 'Employee Number'), field('phone', 'Phone'), field('email', 'Email', 'email'), field('licence_number', 'Licence Number'), field('licence_expiry', 'Licence Expiry', 'date')]),
  def('my-fuel-cards', 'My Fuel Cards', 'Review fuel cards issued to the current account.', [...identity('Fuel Card', 'Card Number'), field('card_type', 'Card Type'), field('vehicle', 'Vehicle'), field('driver', 'Driver'), field('balance', 'Balance', 'currency'), field('expiry_date', 'Expiry Date', 'date')], true),
  def('my-fuel-requests', 'My Fuel Requests', 'Create and manage fuel requests for the current account.', [...identity('Fuel Request', 'Request Number'), field('product_id', 'Fuel Product ID', 'number', true), field('quantity', 'Quantity', 'number', true), field('required_date', 'Required Date', 'date'), field('purpose', 'Purpose', 'textarea')]),
  def('my-orders', 'My Orders', 'Review fuel orders for the current account.', [...identity('Fuel Order', 'Order Number'), field('request_id', 'Request ID', 'number'), field('order_date', 'Order Date', 'date'), field('quantity', 'Quantity', 'number'), field('amount', 'Amount', 'currency'), field('delivery_date', 'Delivery Date', 'date')], true),
  def('my-deliveries', 'My Deliveries', 'Track fuel deliveries for the current account.', [...identity('Delivery', 'Delivery Number'), field('order_id', 'Order ID', 'number'), field('vehicle', 'Delivery Vehicle'), field('driver', 'Driver'), field('scheduled_date', 'Scheduled Date', 'datetime'), field('delivered_quantity', 'Delivered Quantity', 'number')], true),
  def('my-transactions', 'My Transactions', 'Review account transaction history.', [...identity('Transaction', 'Transaction Reference'), field('transaction_type', 'Transaction Type'), ...financial, field('station', 'Station')], true),
  def('my-payments', 'My Payments', 'Review payment history and status.', [...identity('Payment', 'Payment Reference'), field('payment_type', 'Payment Type'), ...financial], true),
  def('my-invoices', 'My Invoices', 'Review invoices issued to the current account.', [...identity('Invoice', 'Invoice Number'), field('invoice_date', 'Invoice Date', 'date'), field('due_date', 'Due Date', 'date'), field('subtotal', 'Subtotal', 'currency'), field('total_amount', 'Total Amount', 'currency'), field('outstanding_amount', 'Outstanding Amount', 'currency')], true),
  def('my-statements', 'My Statements', 'Review and download account statements.', [...identity('Statement', 'Statement Reference'), field('period_start', 'Period Start', 'date'), field('period_end', 'Period End', 'date'), field('opening_balance', 'Opening Balance', 'currency'), field('closing_balance', 'Closing Balance', 'currency'), field('document_url', 'Document URL', 'url')], true),
  def('my-documents', 'My Documents', 'Manage documents associated with the current account.', [...identity('Document Name', 'Document Number'), field('document_type', 'Document Type', 'text', true), field('issue_date', 'Issue Date', 'date'), field('expiry_date', 'Expiry Date', 'date'), field('document_url', 'Document URL', 'url', true)]),
  def('my-notifications', 'My Notifications', 'Review account, transaction, and security notifications.', [...identity('Notification', 'Notification Reference'), field('notification_type', 'Notification Type'), field('message', 'Message', 'textarea'), field('sent_at', 'Sent At', 'datetime'), field('read_at', 'Read At', 'datetime')], true),
  def('my-support-tickets', 'My Support Tickets', 'Create and track support requests.', [...identity('Support Ticket', 'Ticket Number'), field('category', 'Category', 'text', true), field('priority', 'Priority'), field('subject', 'Subject', 'text', true), field('description', 'Description', 'textarea', true), field('assigned_to', 'Assigned To')]),
  def('change-password', 'Change Password', 'Manage password change requests for the signed-in user.', [...identity('Password Change', 'Change Reference'), field('current_password', 'Current Password', 'password', true), field('new_password', 'New Password', 'password', true), field('confirm_password', 'Confirm Password', 'password', true)]),
  def('security-settings', 'Security Settings', 'Manage authentication and account security preferences.', [...identity('Security Setting', 'Setting Reference'), field('two_factor_enabled', 'Two-Factor Authentication'), field('login_alerts', 'Login Alerts'), field('session_timeout', 'Session Timeout', 'number'), field('trusted_devices', 'Trusted Devices', 'textarea')]),
  def('logout', 'Logout', 'End the current authenticated session.', [...identity('Session', 'Session Reference'), field('signed_in_at', 'Signed In At', 'datetime'), field('last_activity', 'Last Activity', 'datetime'), field('device', 'Device'), field('ip_address', 'IP Address')], true),
]

export const myAccountConfigs = definitions.map(createFuelOperationPage)
export const myAccountPageRegistry = Object.fromEntries(myAccountConfigs.map((page) => [page.id, page]))
