import { createFuelOperationPage, type FuelOperationDefinition, type FuelOperationField } from './fuel-operation-page-factory'

const field = (name: string, label: string, type: FuelOperationField['type'] = 'text', required = false): FuelOperationField => ({ name, label, type, required })
const identity = (nameLabel: string, codeLabel = 'Reference') => [field('name', nameLabel, 'text', true), field('code', codeLabel, 'text', true)]
const product = field('product_id', 'Fuel Product ID', 'number', true)
const quantity = field('quantity', 'Quantity', 'number', true)

const definitions: FuelOperationDefinition[] = [
  { slug: 'fuel-products', title: 'Fuel Products', description: 'Manage fuel products available across the network.', icon: 'Fuel', fields: [...identity('Product Name', 'Product Code'), field('category_id', 'Category ID', 'number'), field('unit', 'Unit'), field('octane', 'Octane', 'number'), field('description', 'Description', 'textarea')] },
  { slug: 'product-categories', title: 'Product Categories', description: 'Organize fuel products into operational categories.', icon: 'Tags', fields: [...identity('Category Name', 'Category Code'), field('description', 'Description', 'textarea')] },
  { slug: 'fuel-pricing', title: 'Fuel Pricing', description: 'Manage effective fuel prices and approvals.', icon: 'BadgeDollarSign', fields: [...identity('Price Name'), product, field('selling_price', 'Selling Price', 'currency', true), field('effective_date', 'Effective Date', 'date', true), field('approval_status', 'Approval Status')] },
  { slug: 'inventory-overview', title: 'Inventory Overview', description: 'Review consolidated inventory across storage locations.', icon: 'ChartNoAxesCombined', readOnly: true, fields: [...identity('Location', 'Location Code'), field('product', 'Product'), quantity, field('available_quantity', 'Available Quantity', 'number'), field('stock_value', 'Stock Value', 'currency')] },
  { slug: 'station-stock', title: 'Station Stock', description: 'Track stock held at stations.', icon: 'Store', fields: [...identity('Station', 'Stock Reference'), field('station_id', 'Station ID', 'number', true), product, quantity, field('reorder_level', 'Reorder Level', 'number')] },
  { slug: 'depot-stock', title: 'Depot Stock', description: 'Track stock held at distribution depots.', icon: 'Warehouse', fields: [...identity('Depot', 'Stock Reference'), field('depot_id', 'Depot ID', 'number', true), product, quantity, field('reserved_quantity', 'Reserved Quantity', 'number')] },
  { slug: 'tank-stock', title: 'Tank Stock', description: 'Monitor products held in storage tanks.', icon: 'Cylinder', fields: [...identity('Tank', 'Tank Code'), field('tank_id', 'Tank ID', 'number', true), product, quantity, field('capacity', 'Capacity', 'number')] },
  { slug: 'stock-receipts', title: 'Stock Receipts', description: 'Record incoming fuel stock.', icon: 'PackagePlus', fields: [...identity('Supplier', 'Receipt Number'), product, quantity, field('unit_cost', 'Unit Cost', 'currency'), field('receipt_date', 'Receipt Date', 'date', true)] },
  { slug: 'stock-issues', title: 'Stock Issues', description: 'Record fuel issued from inventory.', icon: 'PackageMinus', fields: [...identity('Issued To', 'Issue Number'), product, quantity, field('issue_date', 'Issue Date', 'date', true), field('reason', 'Reason', 'textarea')] },
  { slug: 'stock-transfers', title: 'Stock Transfers', description: 'Manage transfers between storage locations.', icon: 'ArrowLeftRight', fields: [...identity('Transfer Name', 'Transfer Number'), field('from_location', 'From Location', 'text', true), field('to_location', 'To Location', 'text', true), product, quantity, field('transfer_date', 'Transfer Date', 'date')] },
  { slug: 'stock-adjustments', title: 'Stock Adjustments', description: 'Record authorized inventory adjustments.', icon: 'ListRestart', fields: [...identity('Adjustment Name', 'Adjustment Number'), product, quantity, field('adjustment_type', 'Adjustment Type', 'text', true), field('reason', 'Reason', 'textarea', true)] },
  { slug: 'tank-readings', title: 'Tank Readings', description: 'Capture operational tank measurements.', icon: 'Gauge', fields: [...identity('Tank', 'Reading Reference'), field('tank_id', 'Tank ID', 'number', true), field('reading', 'Reading', 'number', true), field('temperature', 'Temperature', 'number'), field('reading_date', 'Reading Date', 'datetime', true)] },
  { slug: 'dip-readings', title: 'Dip Readings', description: 'Capture manual tank dip measurements.', icon: 'Ruler', fields: [...identity('Tank', 'Dip Reference'), field('tank_id', 'Tank ID', 'number', true), field('dip_level', 'Dip Level', 'number', true), field('calculated_volume', 'Calculated Volume', 'number'), field('reading_date', 'Reading Date', 'datetime', true)] },
  { slug: 'meter-readings', title: 'Meter Readings', description: 'Capture pump and dispensing meter readings.', icon: 'Gauge', fields: [...identity('Meter', 'Reading Reference'), field('meter_id', 'Meter ID', 'number', true), field('opening_reading', 'Opening Reading', 'number', true), field('closing_reading', 'Closing Reading', 'number', true), field('reading_date', 'Reading Date', 'date', true)] },
  { slug: 'physical-stock-counts', title: 'Physical Stock Counts', description: 'Record physical inventory count exercises.', icon: 'ClipboardList', fields: [...identity('Count Name', 'Count Reference'), field('location', 'Location', 'text', true), product, field('system_quantity', 'System Quantity', 'number'), field('counted_quantity', 'Counted Quantity', 'number', true), field('count_date', 'Count Date', 'date', true)] },
  { slug: 'stock-reconciliation', title: 'Stock Reconciliation', description: 'Reconcile physical and system inventory balances.', icon: 'Scale', fields: [...identity('Reconciliation Name'), field('location', 'Location', 'text', true), product, field('system_quantity', 'System Quantity', 'number'), field('physical_quantity', 'Physical Quantity', 'number'), field('variance', 'Variance', 'number'), field('reconciliation_date', 'Date', 'date')] },
  { slug: 'fuel-losses-and-gains', title: 'Fuel Losses and Gains', description: 'Track and investigate inventory variances.', icon: 'TrendingDown', fields: [...identity('Location'), product, field('variance_type', 'Variance Type', 'text', true), quantity, field('value', 'Value', 'currency'), field('recorded_date', 'Recorded Date', 'date')] },
  { slug: 'low-stock-alerts', title: 'Low-Stock Alerts', description: 'Review and manage low-stock notifications.', icon: 'TriangleAlert', fields: [...identity('Location', 'Alert Reference'), product, field('current_quantity', 'Current Quantity', 'number'), field('reorder_level', 'Reorder Level', 'number'), field('alert_date', 'Alert Date', 'datetime')] },
  { slug: 'inventory-valuation', title: 'Inventory Valuation', description: 'Review the financial value of fuel inventory.', icon: 'CircleDollarSign', readOnly: true, fields: [...identity('Location', 'Valuation Reference'), field('product', 'Product'), quantity, field('unit_cost', 'Unit Cost', 'currency'), field('total_value', 'Total Value', 'currency'), field('valuation_date', 'Valuation Date', 'date')] },
]

export const fuelOperationConfigs = definitions.map(createFuelOperationPage)
export const fuelOperationPageRegistry = Object.fromEntries(fuelOperationConfigs.map((page) => [page.id, page]))
